// Generated by assets/brand/generate.py. Edit the generator, not this file.
export const SHIELD_PATH = 'M30.9 4.4Q32 4 33.1 4.4L53 11.2Q55 11.9 55 14V29.5C55 44.6 45.4 55.9 32 60.5C18.6 55.9 9 44.6 9 29.5V14Q9 11.9 11 11.2Z';
export const CHECK_PATH = 'M25.5 13.5L30 17.5L38.5 9.5';
export const CHECK_WIDTH = 3.2;
export const CUTS = [{ y: 21, height: 3 }, { y: 37, height: 3 }];
export const BANDS = [
  { from: '#7DFFD0', to: '#00F5A0', top: 0, bottom: 22.5 },
  { from: '#00E3A8', to: '#00C7B4', top: 22.5, bottom: 38.5 },
  { from: '#06B6D4', to: '#0891B2', top: 38.5, bottom: 64 }
];
