import argparse
import re
import subprocess
import sys
import time

def get_image_digest(image_name):
    try:
        subprocess.run(["docker", "pull", "-q", image_name], check=True, stdout=subprocess.DEVNULL)
        inspect_cmd = ["docker", "inspect", "--format={{index .RepoDigests 0}}", image_name]
        result = subprocess.run(inspect_cmd, capture_output=True, text=True, check=True)
        digest = result.stdout.strip()
        if not digest or "@" not in digest:
            raise ValueError("No digest found")
        return digest
    except Exception as e:
        print(f"Error fetching digest for {image_name}: {e}")
        sys.exit(1)

def create_pull_request(file_path, updates):
    branch_name = f"chore/update-images-{int(time.time())}"
    title = "chore(deps): lock base images to latest secure digests"
    
    body = "### 🛡️ Automated Base Image Security Update\n\n"
    body += "This automated Pull Request updates the base image digests in `docker-bake.hcl` "
    body += "to their latest secure, immutable cryptographic hashes.\n\n"
    body += "| Variable Name | Target Container Reference |\n"
    body += "| :--- | :--- |\n"
    for var_name, locked_value in updates.items():
        body += f"| **`{var_name}`** | `{locked_value}` |\n"
    body += "\n\n*This PR was auto-generated by the automated dependency lock pipeline.*"

    try:
        subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True)
        subprocess.run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"], check=True)
        
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        subprocess.run(["git", "add", file_path], check=True)
        subprocess.run(["git", "commit", "-m", title], check=True)
        subprocess.run(["git", "push", "origin", branch_name], check=True)
        
        pr_cmd = [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", "main",
            "--head", branch_name
        ]
        subprocess.run(pr_cmd, check=True)
        print(f"Successfully created Pull Request for branch: {branch_name}")
    except Exception as e:
        print(f"Failed to automate Git/PR process: {e}")
        sys.exit(1)

def lock_variables_in_hcl(file_path, mappings, enable_pr):
    with open(file_path, "r", encoding="utf-8") as f:
        original_content = f.read()

    content = original_content
    updates_made = {}

    for var_name, image_tag in mappings.items():
        print(f"Resolving: {image_tag}")
        locked_value = get_image_digest(image_tag)
        
        pattern = r'(variable\s+"' + re.escape(var_name) + r'"\s*\{\s*default\s*=\s*")[^"]+("\s*\})'
        match = re.search(pattern, content)
        
        if not match:
            print(f"Warning: Variable '{var_name}' not found in {file_path}")
            continue
            
        current_val = match.group(0)
        if locked_value not in current_val:
            print(f" -> Change detected. New lock value: {locked_value}")
            content = re.sub(pattern, r'\1' + locked_value + r'\2', content)
            updates_made[var_name] = locked_value
        else:
            print(f" -> No change needed for '{var_name}'")

    if not updates_made:
        print("All images are already up-to-date. No changes detected.")
        return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {file_path} successfully.")

    if enable_pr:
        print("Starting Automated Pull Request Process...")
        create_pull_request(file_path, updates_made)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Lock bake HCL images and optionally create a Pull Request.")
    parser.add_argument("--pull-request", action="store_true", help="Automate git commit, push, and PR creation if updates are found.")
    args = parser.parse_args()

    hcl_file = "docker-bake.hcl"
    dependencies = {
        "BASE_IMAGE": "cgr.dev/chainguard/wolfi-base:latest",
    }

    lock_variables_in_hcl(hcl_file, dependencies, args.pull_request)