import argparse
import re
import subprocess
import sys
import time

def get_image_digest(image_name):
    try:
        subprocess.run(["docker", "pull", "-q", image_name], check=True, stdout=subprocess.DEVNULL)
        inspect_cmd = ["docker", "inspect", "--format={{index .RepoDigests 0}}", image_name]
        result = subprocess.run(inspect_cmd, capture_output=True, text=True, check=True)
        digest = result.stdout.strip().split('\n')[-1].strip()
        if not digest or "@" not in digest:
            raise ValueError("No digest found")
        return digest
    except Exception as e:
        print(f"Error fetching digest for {image_name}: {e}")
        sys.exit(1)

def get_wolfi_package_version(runner_image, package_name):
    try:
        subprocess.run(["docker", "pull", "-q", runner_image], check=True, stdout=subprocess.DEVNULL)
    except Exception as e:
        print(f"Error pulling runner image {runner_image}: {e}")
        sys.exit(1)

    script = f"apk update > /dev/null && apk search -x {package_name}"
    try:
        res = subprocess.run(
            ["docker", "run", "--rm", "--pull", "always", runner_image, "sh", "-c", script],
            capture_output=True, text=True, check=True, timeout=120
        )
        prefix = f"{package_name}-"
        for line in res.stdout.strip().split("\n"):
            line = line.strip()
            if line.startswith(prefix):
                candidate = line[len(prefix):].strip()
                if candidate and candidate[0].isdigit():
                    return candidate
        raise ValueError(f"Package {package_name} not found in search results")
    except Exception as e:
        print(f"Error fetching package version for {package_name}: {e}")
        sys.exit(1)

def create_pull_request(file_path, updates):
    branch_name = f"chore/security-updates-{int(time.time())}"
    title = "chore(deps): lock base images and package versions to latest secure releases"

    body = "### 🛡️ Automated Dependency & Security Update\n\n"
    body += "This automated Pull Request updates the cryptographic digests of base images "
    body += "and pins Wolfi system package versions to their latest stable releases inside `docker-bake.hcl`.\n\n"
    body += "| Variable Name | Type | Target Reference | Locked Value |\n"
    body += "| :--- | :--- | :--- | :--- |\n"
    for var_name, info in updates.items():
        body += f"| **`{var_name}`** | {info['type']} | `{info['target']}` | `{info['value']}` |\n"
    body += "\n\n*This PR was auto-generated by the automated dependency lock pipeline.*"

    try:
        subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True)
        subprocess.run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"], check=True)

        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        subprocess.run(["git", "add", file_path], check=True)
        subprocess.run(["git", "commit", "-m", title], check=True)
        subprocess.run(["git", "push", "origin", branch_name], check=True)

        pr_cmd = [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", "main",
            "--head", branch_name
        ]
        subprocess.run(pr_cmd, check=True)
        print(f"Successfully created Pull Request for branch: {branch_name}")
    except Exception as e:
        print(f"Failed to automate Git/PR process: {e}")
        sys.exit(1)

def lock_dependencies(file_path, images_map, packages_map, runner_image, enable_pr):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    updates_made = {}

    for var_name, image_tag in images_map.items():
        print(f"Resolving Docker Image: {image_tag}")
        locked_value = get_image_digest(image_tag)

        pattern = r'(variable\s+"' + re.escape(var_name) + r'"\s*\{\s*default\s*=\s*")[^"\r\n]+(")'
        match = re.search(pattern, content)
        if not match:
            print(f" -> WARNING: variable {var_name} not found in {file_path}, skipping.")
            continue
        if locked_value not in match.group(0):
            print(f" -> Updating {var_name} to: {locked_value}")
            content = re.sub(pattern, lambda m: m.group(1) + locked_value + m.group(2), content)
            updates_made[var_name] = {"type": "Docker Image", "target": image_tag, "value": locked_value}

    for var_name, pkg_name in packages_map.items():
        print(f"Resolving Wolfi Package: {pkg_name}")
        locked_value = get_wolfi_package_version(runner_image, pkg_name)

        pattern = r'(variable\s+"' + re.escape(var_name) + r'"\s*\{\s*default\s*=\s*")[^"\r\n]+(")'
        match = re.search(pattern, content)
        if not match:
            print(f" -> WARNING: variable {var_name} not found in {file_path}, skipping.")
            continue
        if locked_value not in match.group(0):
            print(f" -> Updating {var_name} to: {locked_value}")
            content = re.sub(pattern, lambda m: m.group(1) + locked_value + m.group(2), content)
            updates_made[var_name] = {"type": "Wolfi Package", "target": pkg_name, "value": locked_value}

    if not updates_made:
        print("All dependencies are already locked to the latest versions. No changes detected.")
        return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {file_path} successfully.")

    if enable_pr:
        print("Changes detected. Triggering Pull Request Automation...")
        create_pull_request(file_path, updates_made)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--pull-request", action="store_true")
    args = parser.parse_args()

    hcl_file = "docker-bake.hcl"
    runner_image_ref = "cgr.dev/chainguard/wolfi-base:latest"

    images_to_lock = {
        "BASE_IMAGE": "cgr.dev/chainguard/wolfi-base:latest"
    }

    packages_to_lock = {
        "NODE_22_FULL_VERSION": "nodejs-22",
        "NODE_24_FULL_VERSION": "nodejs-24"
    }

    lock_dependencies(hcl_file, images_to_lock, packages_to_lock, runner_image_ref, args.pull_request)
