site_name: Node.js Secure Environment Dashboard
site_description: High-Assurance Zero-CVE Node.js Container Hardening and Security Reports
site_author: Taha Samy
repo_name: taha2samy-3/node
repo_url: https://github.com/taha2samy-3/node

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - charts
  - macros:
      module_name: main

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - tables
  - attr_list
  - def_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

nav:
  - Home: index.md
  - Node 22 LTS: node-22.md
  - Node 24 LTS: node-24.md
  - Python 3.10: python-3.10.md
  - Python 3.11: python-3.11.md
  - Python 3.12: python-3.12.md
  - Python 3.13: python-3.13.md
  - Python 3.14: python-3.14.md