ARG BASE_IMAGE=cgr.dev/chainguard/wolfi-base:latest
ARG NODE_VERSION=22
ARG NODE_FULL_VERSION

FROM ${BASE_IMAGE} AS full-dev

ARG NODE_VERSION
ARG NODE_FULL_VERSION

USER root

RUN apk update && apk add --no-cache \
    nodejs-${NODE_VERSION}=${NODE_FULL_VERSION} \
    npm

RUN adduser -D -u 1000 node && \
    mkdir /app && chown node:node /app

COPY nodejs/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
RUN chmod +x /usr/bin/docker-entrypoint.sh

WORKDIR /app
USER node

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
CMD ["node"]

FROM ${BASE_IMAGE} AS minimal-prep

ARG NODE_VERSION
ARG NODE_FULL_VERSION

USER root

RUN apk update && apk add --no-cache \
    nodejs-${NODE_VERSION}-minimal-compat=${NODE_FULL_VERSION} \
    tini

RUN adduser -D -u 1000 node && \
    mkdir /app && chown node:node /app

COPY nodejs/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
RUN chmod +x /usr/bin/docker-entrypoint.sh

FROM minimal-prep AS minimal-cleaner

RUN rm -rf \
    /lib/apk/db \
    /var/cache/apk \
    /etc/apk \
    /usr/share/apk \
    /usr/share/man \
    /usr/share/doc \
    /tmp/*

FROM scratch AS minimal

COPY --from=minimal-cleaner / /

ENV NODE_ENV=production
WORKDIR /app
USER node

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/docker-entrypoint.sh"]
CMD ["node"]
