name: Renovate Dependency Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.17
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}